# Generated by Django 5.2.8 on 2026-04-26 14:52

import django.core.validators
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='maintenance',
            options={'ordering': ['-started_at', '-created_at']},
        ),
        migrations.AddField(
            model_name='maintenance',
            name='estimated_duration_hours',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='maintenance',
            name='started_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
